FROM python:latest

# Definir las variables como argumentos de build
ARG SLACK_BOT_TOKEN
ARG SLACK_APP_TOKEN
ARG OPENAI_API_KEY
ARG CHATGPT_MODEL
ARG DALLE_MODEL
ARG SIGNING_SECRET
ARG GOOGLE_API_KEY
ARG GEMINI_MODEL
ARG CLAUDE_API_KEY
ARG CLAUDE_MODEL
ARG GEPPETTO_VERSION

# Exportar las variables como variables de entorno para tiempo de ejecución
ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV CHATGPT_MODEL=${CHATGPT_MODEL}
ENV DALLE_MODEL=${DALLE_MODEL}
ENV SIGNING_SECRET=${SIGNING_SECRET}
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
ENV GEMINI_MODEL=${GEMINI_MODEL}
ENV CLAUDE_API_KEY=${CLAUDE_API_KEY}
ENV CLAUDE_MODEL=${CLAUDE_MODEL}
ENV GEPPETTO_VERSION=${GEPPETTO_VERSION}


RUN apt-get -y update && apt-get -y upgrade
RUN python -m pip install --upgrade pip
RUN python -m pip install poetry
ADD . /app/
WORKDIR /app
RUN poetry install
CMD [ "poetry", "run", "geppetto" ]
