# Despliegue del contenedor en Kubernetes de forma local

name: Build and Deploy to Kubernetes
on:
  push:
    branches: [ "Staging" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1
  SERVICE_NAME: cloud-run-jobs
  REPOSITORY: docker-repository
  IMAGE: geppetto
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configurar kubectl
    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    # Crear directorio ~/.kube si no existe
    - name: Create kube directory
      run: |
        mkdir -p $HOME/.kube

    # Configurar KUBECONFIG
    - name: Set up KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    # Autenticar en Google Cloud
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: '${{ secrets.GCLOUD_KEY_JSON }}'

    # Autenticar gcloud
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_KEY_JSON }}'
        token_format: 'access_token'

    # Autenticar Docker con Google Artifact Registry
    - name: Authenticate Docker to Google Artifact Registry
      env:
        ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
      run: |
        echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev

    # Compilar imagen Docker
    - name: Build Docker image
      run: |
        docker build . --platform linux/amd64 -t geppetto:latest \
          --tag us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    # Publicar imagen Docker
    - name: Publish
      run: |
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    # Desplegar en Kubernete-
    - name: Deploy to Kubernetes
      run: |
       KUBECONFIG=$HOME/.kube/config kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
