# Despliegue del contenedor en Kubernetes de forma local

name: Build and Deploy to Kubernetes
on:
  push:
    branches: [ "Staging" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1
  SERVICE_NAME: cloud-run-jobs
  REPOSITORY: docker-repository
  IMAGE: geppetto
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configurar kubectl
    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    # Crear directorio ~/.kube si no existe
    - name: Create kube directory
      run: |
        mkdir -p $HOME/.kube

    # Configurar KUBECONFIG
    - name: Set up KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    # Autenticar en Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: '${{ secrets.GCLOUD_KEY_JSON }}'
    
    # Build Docker image
    - name: Build Docker image
      run: |
        docker build . --platform linux/amd64 -t geppetto:latest \
          --tag us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    # Publish Docker image
    - name: Publish
      run: |
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: $HOME/.kube/config
      run: |
        kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
